### PR TITLE
SLING-9715 - The JavaUseProvider does not properly handle the adaptable argument for Sling Model classes

### PR DESCRIPTION
**Pull request by paul-bjorkstrand**
When Sling Models instantiation was added in SLING-9320 ([commit][1]), it did not treat the `adaptable` argument the same for all types of instantiations (Sling Models vs basic Sling Adaptable). This fixes that by rearranging the instantiation attempt order, which puts the argument provided adaptable through `ModelFactory#createModel` just like the request and resource would be.

This is a subtle semantic change, and likely warrants a minor version update.

[1]: https://github.com/apache/sling-org-apache-sling-scripting-sightly/commit/bcd46027e09182911c55bb244d42debb1bd367c7

### CODE REVIEW

**Comment by raducotescu** [comment]
@paul-bjorkstrand, can you please create a SLING issue and link the PR to it? I'll have a look tomorrow, to make sure that the IT still passes.

**Comment by paul-bjorkstrand** [comment]
@raducotescu: https://issues.apache.org/jira/browse/SLING-9715

**Comment by raducotescu** [comment]
Applied a slightly modified patch in 960d9cd. Had to replace:

```java
if (adaptable != null && modelFactory.canCreateFromAdaptable(adaptable, cls)) {
    LOG.debug("Trying to instantiate class {} as Sling Model from provided adaptable.", cls);
    return ProviderOutcome.notNullOrFailure(modelFactory.createModel(request, cls));
}
```

with

```java
if (adaptable != null && modelFactory.canCreateFromAdaptable(adaptable, cls)) {
    LOG.debug("Trying to instantiate class {} as Sling Model from provided adaptable.", cls);
    return ProviderOutcome.notNullOrFailure(modelFactory.createModel(adaptable, cls));
}
```

**Comment by paul-bjorkstrand** [comment]
Ah, I gotta watch that copy-pasta. I sheepishly admit that my quick test with it was using the current resource, rather than a different one, so clearly I did not exercise that path. 😞 

Thanks for that catch, @raducotescu.

I will also say, that I was inches away from creating a unit test for that, but shied away due to the sheer weight of the setup code needed. To make it more easily testable, will require some significant reorganization of that class' methods.

**Pull request closed without merging**
